[package]
name = "server_express_core"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
libc = "0.2.178"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.145"
ssh2 = "0.9"

[lib]
crate-type = ["cdylib"]
